# Generated by Django 4.2.1 on 2023-06-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatarurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(default='http://43.143.140.26/avatars/29.jpg', max_length=1024),
        ),
    ]
