# Generated by Django 4.1.7 on 2023-06-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("information", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="userId",
            new_name="userID",
        ),
        migrations.RenameField(
            model_name="favorite",
            old_name="userId",
            new_name="userID",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="userId",
            new_name="userID",
        ),
    ]
