# Generated by Django 4.2.1 on 2023-06-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_rename_userid_comment_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='videoId',
            new_name='videoID',
        ),
    ]
